TADS:
  RAW: "data/Dixon_2015_stability_formatted_TADs.bed"
  ANNOTATED: "data/Annotated_Default_TADs.p"

ANNOTATIONS:
  GENES: "data/gnomad_genes_pli_loeuf_HI.bed"
  EXONS: "data/HAVANA_exon.merged.bed.gz"
  ENHANCERS: "data/fantom5_enhancer_phastcon_average.bed"
  CTCF: "data/H1_hESC_CTCF_peaks_idr_optimal.bed"
  DDG2P: "data/DDG2P_genes.bed"
  POINT: "data/extracted_po_pairs.bed"

CNVS:
  RAW:
    NON_PATHOGENIC:
    PATHOGENIC: 
  ANNOTATED:
    NON_PATHOGENIC:
    PATHOGENIC:

FEATURES: "extended"

CLASSIFIER: "rf"

KWARGS:
  max_depth:  100
  max_features: 'log2'
  min_samples_leaf: 5
  min_samples_split: 10
  n_estimators: 300
  oob_score: True

PRETRAINED_MODEL:
